<?php
/**
 * ACF field groups for the NJB Customizations plugin.
 *
 * @package NJB_Customizations
 */
if ( ! defined( 'ABSPATH' ) ) { 
    exit; // Exit if accessed directly.
}

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
        array(
            'key' => 'group_685d1e5fd6dbd',
            'title' => 'Donations',
            'fields' => array(
                array(
                    'key' => 'field_685d1e609166e',
                    'label' => 'Amount donated',
                    'name' => 'amount_donated',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'donations',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'side',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'page_attributes',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
            'active' => true,
            'description' => '',
            'show_in_rest' => 1,
        ) 
    );

	acf_add_local_field_group(
        array(
            'key' => 'group_6871352781d51',
            'title' => 'Events',
            'fields' => array(
                array(
                    'key' => 'field_68713528275c8',
                    'label' => 'External Link',
                    'name' => 'external_link',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'tribe_events',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 1,
        )
    );

	acf_add_local_field_group(
        array(
            'key' => 'group_686af5a58e1c5',
            'title' => 'Pages',
            'fields' => array(
                array(
                    'key' => 'field_686af5a51e502',
                    'label' => 'Headline',
                    'name' => 'headline',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 1,
        )
    );

    acf_add_local_field_group(
        array(
            'key' => 'group_689dc056bc04c',
            'title' => 'Business',
            'fields' => array(
                array(
                    'key' => 'field_689e05b5aa1b8',
                    'label' => 'Business Name',
                    'name' => 'business_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_689dc057d6517',
                    'label' => 'Sector/Industry',
                    'name' => 'sectorindustry',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Fashion & Apparel' => 'Fashion & Apparel',
                        'Beauty & Wellness' => 'Beauty & Wellness',
                        'Food & Beverage' => 'Food & Beverage',
                        'Events & Entertainment' => 'Events & Entertainment',
                        'Education & Training' => 'Education & Training',
                        'Finance & Investment' => 'Finance & Investment',
                        'Technology & Digital Services' => 'Technology & Digital Services',
                        'Real Estate & Housing' => 'Real Estate & Housing',
                        'Healthcare & Medical' => 'Healthcare & Medical',
                        'Nonprofit & Community' => 'Nonprofit & Community',
                        'Retail & E-commerce' => 'Retail & E-commerce',
                        'Consulting & Professional Services' => 'Consulting & Professional Services',
                        'Travel & Hospitality' => 'Travel & Hospitality',
                        'Arts & Creative' => 'Arts & Creative',
                        'Media & Communications' => 'Media & Communications',
                        'Logistics & Transportation' => 'Logistics & Transportation',
                        'Home & Lifestyle' => 'Home & Lifestyle',
                        'Agriculture & Sustainability' => 'Agriculture & Sustainability',
                        'Legal & Compliance' => 'Legal & Compliance',
                        'Others' => 'Others',
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                array(
                    'key' => 'field_689dc076d6518',
                    'label' => 'Address',
                    'name' => 'address',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'address-section',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_689e068b52813',
                            'label' => 'Country',
                            'name' => 'country',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'country_to_state',
                                'id' => '',
                            ),
                            'choices' => array(
                                '\'\'' => 'Select a country / region',
                                'AX' => 'Åland Islands',
                                'AL' => 'Albania',
                                'DZ' => 'Algeria',
                                'AS' => 'American Samoa',
                                'AD' => 'Andorra',
                                'AO' => 'Angola',
                                'AI' => 'Anguilla',
                                'AQ' => 'Antarctica',
                                'AG' => 'Antigua and Barbuda',
                                'AR' => 'Argentina',
                                'AM' => 'Armenia',
                                'AW' => 'Aruba',
                                'AU' => 'Australia',
                                'AT' => 'Austria',
                                'AZ' => 'Azerbaijan',
                                'BS' => 'Bahamas',
                                'BH' => 'Bahrain',
                                'BD' => 'Bangladesh',
                                'BB' => 'Barbados',
                                'BY' => 'Belarus',
                                'PW' => 'Belau',
                                'BE' => 'Belgium',
                                'BZ' => 'Belize',
                                'BJ' => 'Benin',
                                'BM' => 'Bermuda',
                                'BT' => 'Bhutan',
                                'BO' => 'Bolivia',
                                'BQ' => 'Bonaire, Saint Eustatius and Saba',
                                'BA' => 'Bosnia and Herzegovina',
                                'BW' => 'Botswana',
                                'BV' => 'Bouvet Island',
                                'BR' => 'Brazil',
                                'IO' => 'British Indian Ocean Territory',
                                'BN' => 'Brunei',
                                'BG' => 'Bulgaria',
                                'BF' => 'Burkina Faso',
                                'BI' => 'Burundi',
                                'KH' => 'Cambodia',
                                'CM' => 'Cameroon',
                                'CA' => 'Canada',
                                'CV' => 'Cape Verde',
                                'KY' => 'Cayman Islands',
                                'CF' => 'Central African Republic',
                                'TD' => 'Chad',
                                'CL' => 'Chile',
                                'CN' => 'China',
                                'CX' => 'Christmas Island',
                                'CC' => 'Cocos (Keeling) Islands',
                                'CO' => 'Colombia',
                                'KM' => 'Comoros',
                                'CG' => 'Congo (Brazzaville)',
                                'CD' => 'Congo (Kinshasa)',
                                'CK' => 'Cook Islands',
                                'CR' => 'Costa Rica',
                                'HR' => 'Croatia',
                                'CU' => 'Cuba',
                                'CW' => 'Cura&ccedil;ao',
                                'CY' => 'Cyprus',
                                'CZ' => 'Czech Republic',
                                'DK' => 'Denmark',
                                'DJ' => 'Djibouti',
                                'DM' => 'Dominica',
                                'DO' => 'Dominican Republic',
                                'EC' => 'Ecuador',
                                'EG' => 'Egypt',
                                'SV' => 'El Salvador',
                                'GQ' => 'Equatorial Guinea',
                                'ER' => 'Eritrea',
                                'EE' => 'Estonia',
                                'SZ' => 'Eswatini',
                                'ET' => 'Ethiopia',
                                'FK' => 'Falkland Islands',
                                'FO' => 'Faroe Islands',
                                'FJ' => 'Fiji',
                                'FI' => 'Finland',
                                'FR' => 'France',
                                'GF' => 'French Guiana',
                                'PF' => 'French Polynesia',
                                'TF' => 'French Southern Territories',
                                'GA' => 'Gabon',
                                'GM' => 'Gambia',
                                'GE' => 'Georgia',
                                'DE' => 'Germany',
                                'GH' => 'Ghana',
                                'GI' => 'Gibraltar',
                                'GR' => 'Greece',
                                'GL' => 'Greenland',
                                'GD' => 'Grenada',
                                'GP' => 'Guadeloupe',
                                'GU' => 'Guam',
                                'GT' => 'Guatemala',
                                'GG' => 'Guernsey',
                                'GN' => 'Guinea',
                                'GW' => 'Guinea-Bissau',
                                'GY' => 'Guyana',
                                'HT' => 'Haiti',
                                'HM' => 'Heard Island and McDonald Islands',
                                'HN' => 'Honduras',
                                'HK' => 'Hong Kong',
                                'HU' => 'Hungary',
                                'IS' => 'Iceland',
                                'IN' => 'India',
                                'ID' => 'Indonesia',
                                'IR' => 'Iran',
                                'IQ' => 'Iraq',
                                'IE' => 'Ireland',
                                'IM' => 'Isle of Man',
                                'IL' => 'Israel',
                                'IT' => 'Italy',
                                'CI' => 'Ivory Coast',
                                'JM' => 'Jamaica',
                                'JP' => 'Japan',
                                'JE' => 'Jersey',
                                'JO' => 'Jordan',
                                'KZ' => 'Kazakhstan',
                                'KE' => 'Kenya',
                                'KI' => 'Kiribati',
                                'KW' => 'Kuwait',
                                'KG' => 'Kyrgyzstan',
                                'LA' => 'Laos',
                                'LV' => 'Latvia',
                                'LB' => 'Lebanon',
                                'LS' => 'Lesotho',
                                'LR' => 'Liberia',
                                'LY' => 'Libya',
                                'LI' => 'Liechtenstein',
                                'LT' => 'Lithuania',
                                'LU' => 'Luxembourg',
                                'MO' => 'Macao',
                                'MG' => 'Madagascar',
                                'MW' => 'Malawi',
                                'MY' => 'Malaysia',
                                'MV' => 'Maldives',
                                'ML' => 'Mali',
                                'MT' => 'Malta',
                                'MH' => 'Marshall Islands',
                                'MQ' => 'Martinique',
                                'MR' => 'Mauritania',
                                'MU' => 'Mauritius',
                                'YT' => 'Mayotte',
                                'MX' => 'Mexico',
                                'FM' => 'Micronesia',
                                'MD' => 'Moldova',
                                'MC' => 'Monaco',
                                'MN' => 'Mongolia',
                                'ME' => 'Montenegro',
                                'MS' => 'Montserrat',
                                'MA' => 'Morocco',
                                'MZ' => 'Mozambique',
                                'MM' => 'Myanmar',
                                'NA' => 'Namibia',
                                'NR' => 'Nauru',
                                'NP' => 'Nepal',
                                'NL' => 'Netherlands',
                                'NC' => 'New Caledonia',
                                'NZ' => 'New Zealand',
                                'NI' => 'Nicaragua',
                                'NE' => 'Niger',
                                'NG' => 'Nigeria',
                                'NU' => 'Niue',
                                'NF' => 'Norfolk Island',
                                'KP' => 'North Korea',
                                'MK' => 'North Macedonia',
                                'MP' => 'Northern Mariana Islands',
                                'NO' => 'Norway',
                                'OM' => 'Oman',
                                'PK' => 'Pakistan',
                                'PS' => 'Palestinian Territory',
                                'PA' => 'Panama',
                                'PG' => 'Papua New Guinea',
                                'PY' => 'Paraguay',
                                'PE' => 'Peru',
                                'PH' => 'Philippines',
                                'PN' => 'Pitcairn',
                                'PL' => 'Poland',
                                'PT' => 'Portugal',
                                'PR' => 'Puerto Rico',
                                'QA' => 'Qatar',
                                'RE' => 'Reunion',
                                'RO' => 'Romania',
                                'RU' => 'Russia',
                                'RW' => 'Rwanda',
                                'BL' => 'Saint Barth&eacute;lemy',
                                'SH' => 'Saint Helena',
                                'KN' => 'Saint Kitts and Nevis',
                                'LC' => 'Saint Lucia',
                                'SX' => 'Saint Martin (Dutch part)',
                                'MF' => 'Saint Martin (French part)',
                                'PM' => 'Saint Pierre and Miquelon',
                                'VC' => 'Saint Vincent and the Grenadines',
                                'WS' => 'Samoa',
                                'SM' => 'San Marino',
                                'ST' => 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe',
                                'SA' => 'Saudi Arabia',
                                'SN' => 'Senegal',
                                'RS' => 'Serbia',
                                'SC' => 'Seychelles',
                                'SL' => 'Sierra Leone',
                                'SG' => 'Singapore',
                                'SK' => 'Slovakia',
                                'SI' => 'Slovenia',
                                'SB' => 'Solomon Islands',
                                'SO' => 'Somalia',
                                'ZA' => 'South Africa',
                                'GS' => 'South Georgia/Sandwich Islands',
                                'KR' => 'South Korea',
                                'SS' => 'South Sudan',
                                'ES' => 'Spain',
                                'LK' => 'Sri Lanka',
                                'SD' => 'Sudan',
                                'SR' => 'Suriname',
                                'SJ' => 'Svalbard and Jan Mayen',
                                'SE' => 'Sweden',
                                'CH' => 'Switzerland',
                                'SY' => 'Syria',
                                'TW' => 'Taiwan',
                                'TJ' => 'Tajikistan',
                                'TZ' => 'Tanzania',
                                'TH' => 'Thailand',
                                'TL' => 'Timor-Leste',
                                'TG' => 'Togo',
                                'TK' => 'Tokelau',
                                'TO' => 'Tonga',
                                'TT' => 'Trinidad and Tobago',
                                'TN' => 'Tunisia',
                                'TR' => 'Turkey',
                                'TM' => 'Turkmenistan',
                                'TC' => 'Turks and Caicos Islands',
                                'TV' => 'Tuvalu',
                                'UG' => 'Uganda',
                                'UA' => 'Ukraine',
                                'AE' => 'United Arab Emirates',
                                'GB' => 'United Kingdom (UK)',
                                'US' => 'United States (US)',
                                'UM' => 'United States (US) Minor Outlying Islands',
                                'UY' => 'Uruguay',
                                'UZ' => 'Uzbekistan',
                                'VU' => 'Vanuatu',
                                'VA' => 'Vatican',
                                'VE' => 'Venezuela',
                                'VN' => 'Vietnam',
                                'VG' => 'Virgin Islands (British)',
                                'VI' => 'Virgin Islands (US)',
                                'WF' => 'Wallis and Futuna',
                                'EH' => 'Western Sahara',
                                'YE' => 'Yemen',
                                'ZM' => 'Zambia',
                                'ZW' => 'Zimbabwe',
                            ),
                            'default_value' => '\'\'',
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'allow_in_bindings' => 0,
                            'ui' => 1,
                            'ajax' => 0,
                            'placeholder' => '',
                            'create_options' => 0,
                            'save_options' => 0,
                        ),
                        array(
                            'key' => 'field_689e069352814',
                            'label' => 'State/province',
                            'name' => 'stateprovince',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'business-state',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_689e06a052815',
                            'label' => 'City',
                            'name' => 'city',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_689e06a752816',
                            'label' => 'Postal Code',
                            'name' => 'postal_code',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_689e06b652817',
                            'label' => 'Street Address',
                            'name' => 'street_address',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_689dc0c9d6519',
                    'label' => 'Phone Number',
                    'name' => 'phone_number',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_689dc0f1d651a',
                    'label' => 'Small Business Logo/Icon',
                    'name' => 'small_business_logoicon',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'allow_in_bindings' => 0,
                    'preview_size' => 'medium',
                ),
                array(
                    'key' => 'field_689dc11cd651b',
                    'label' => 'Email',
                    'name' => 'email',
                    'aria-label' => '',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_689dc12ad651c',
                    'label' => 'website',
                    'name' => 'website',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_689e06db0108a',
                    'label' => 'Approved',
                    'name' => 'approved',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'allow_in_bindings' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'business',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) 
    );
} );
